title: Swanoop Ramakrishnan
description: Cybersecurity Engineer | IT & OT
url: https://swanoop.github.io
baseurl: ""
permalink: /blog/:title/
markdown: kramdown
highlighter: rouge
timezone: Europe/London
plugins:
  - jekyll-feed
exclude:
  - README.md
